name: Code Analysis
on: pull_request

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ESLint
        run: npx eslint . --format=json > eslint-report.json

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report
          path: eslint-report.json
